// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ThirdOpinion.DataFlow.TestHarness.Persistence;

#nullable disable

namespace ThirdOpinion.DataFlow.TestHarness.Persistence.Migrations
{
    [DbContext(typeof(DataFlowTestDbContext))]
    [Migration("20251110030853_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ThirdOpinion.DataFlow.EntityFramework.Entities.ArtifactEntity", b =>
                {
                    b.Property<Guid>("ArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ResourceRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("StoragePath")
                        .HasColumnType("text");

                    b.Property<string>("StorageType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("ArtifactId");

                    b.HasIndex("ResourceRunId", "StepName", "ArtifactName")
                        .IsUnique();

                    b.ToTable("artifacts", (string)null);
                });

            modelBuilder.Entity("ThirdOpinion.DataFlow.EntityFramework.Entities.PipelineRunEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("CompletedResources")
                        .HasColumnType("integer");

                    b.Property<string>("Configuration")
                        .HasColumnType("jsonb");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedResources")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ParentRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("RunType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SkippedResources")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TotalResources")
                        .HasColumnType("integer");

                    b.HasKey("RunId");

                    b.HasIndex("ParentRunId");

                    b.HasIndex("Category", "Name");

                    b.ToTable("pipeline_runs", (string)null);
                });

            modelBuilder.Entity("ThirdOpinion.DataFlow.EntityFramework.Entities.ResourceRunEntity", b =>
                {
                    b.Property<Guid>("ResourceRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ErrorStep")
                        .HasColumnType("text");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ProcessingTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("ResourceRunId");

                    b.HasIndex("Status");

                    b.HasIndex("PipelineRunId", "ResourceId")
                        .IsUnique();

                    b.ToTable("resource_runs", (string)null);
                });

            modelBuilder.Entity("ThirdOpinion.DataFlow.EntityFramework.Entities.StepProgressEntity", b =>
                {
                    b.Property<Guid>("StepProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("ResourceRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("StepProgressId");

                    b.HasIndex("ResourceRunId", "Sequence");

                    b.ToTable("step_progress", (string)null);
                });

            modelBuilder.Entity("ThirdOpinion.DataFlow.EntityFramework.Entities.ArtifactEntity", b =>
                {
                    b.HasOne("ThirdOpinion.DataFlow.EntityFramework.Entities.ResourceRunEntity", "ResourceRun")
                        .WithMany("Artifacts")
                        .HasForeignKey("ResourceRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceRun");
                });

            modelBuilder.Entity("ThirdOpinion.DataFlow.EntityFramework.Entities.PipelineRunEntity", b =>
                {
                    b.HasOne("ThirdOpinion.DataFlow.EntityFramework.Entities.PipelineRunEntity", "ParentRun")
                        .WithMany("ChildRuns")
                        .HasForeignKey("ParentRunId");

                    b.Navigation("ParentRun");
                });

            modelBuilder.Entity("ThirdOpinion.DataFlow.EntityFramework.Entities.ResourceRunEntity", b =>
                {
                    b.HasOne("ThirdOpinion.DataFlow.EntityFramework.Entities.PipelineRunEntity", "PipelineRun")
                        .WithMany("ResourceRuns")
                        .HasForeignKey("PipelineRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PipelineRun");
                });

            modelBuilder.Entity("ThirdOpinion.DataFlow.EntityFramework.Entities.StepProgressEntity", b =>
                {
                    b.HasOne("ThirdOpinion.DataFlow.EntityFramework.Entities.ResourceRunEntity", "ResourceRun")
                        .WithMany("StepProgresses")
                        .HasForeignKey("ResourceRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceRun");
                });

            modelBuilder.Entity("ThirdOpinion.DataFlow.EntityFramework.Entities.PipelineRunEntity", b =>
                {
                    b.Navigation("ChildRuns");

                    b.Navigation("ResourceRuns");
                });

            modelBuilder.Entity("ThirdOpinion.DataFlow.EntityFramework.Entities.ResourceRunEntity", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("StepProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
