name: 'Get Version from GitVersion'
description: 'Determines version using GitVersion with ContinuousDeployment mode (each commit = one patch increment)'

inputs:
  config_file_path:
    description: 'Path to GitVersion config file'
    required: false
    default: '.gitversion.yml'

outputs:
  formatted_version:
    description: 'Formatted version without commit count (e.g., 1.1.11-preview)'
    value: ${{ steps.version.outputs.formatted_version }}
  base_version:
    description: 'Base version without pre-release label (e.g., 1.1.11)'
    value: ${{ steps.version.outputs.base_version }}
  sem_ver:
    description: 'SemVer with commit count (e.g., 1.1.11-preview.108)'
    value: ${{ steps.version.outputs.sem_ver }}
  full_sem_ver:
    description: 'Full SemVer with build metadata'
    value: ${{ steps.version.outputs.full_sem_ver }}
  assembly_sem_ver:
    description: 'Assembly SemVer (for assembly versioning)'
    value: ${{ steps.version.outputs.assembly_sem_ver }}
  assembly_sem_file_ver:
    description: 'Assembly SemFileVer (for file versioning)'
    value: ${{ steps.version.outputs.assembly_sem_file_ver }}
  is_prerelease:
    description: 'Whether this is a pre-release version'
    value: ${{ steps.version.outputs.is_prerelease }}
  branch_name:
    description: 'Current branch name'
    value: ${{ steps.version.outputs.branch_name }}
  major:
    description: 'Major version number'
    value: ${{ steps.version.outputs.major }}
  minor:
    description: 'Minor version number'
    value: ${{ steps.version.outputs.minor }}
  patch:
    description: 'Patch version number'
    value: ${{ steps.version.outputs.patch }}

runs:
  using: 'composite'
  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.2.0
      with:
        versionSpec: '6.4.x'

    - name: Execute GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v4.2.0
      with:
        configFilePath: ${{ inputs.config_file_path }}

    - name: Format version with commit-based increment
      id: version
      shell: bash
      run: |
        MAJOR="${{ steps.gitversion.outputs.major }}"
        MINOR="${{ steps.gitversion.outputs.minor }}"
        BASE_PATCH="${{ steps.gitversion.outputs.patch }}"
        COMMITS_SINCE_VERSION="${{ steps.gitversion.outputs.commitsSinceVersionSource }}"
        PRE_RELEASE_LABEL="${{ steps.gitversion.outputs.preReleaseLabel }}"
        ORIGINAL_SEMVER="${{ steps.gitversion.outputs.semVer }}"
        BRANCH_NAME="${{ steps.gitversion.outputs.branchName }}"
        
        # Detect preview branches (develop, fix branches)
        IS_PREVIEW_BRANCH=false
        if [[ "$BRANCH_NAME" =~ ^(develop|fix|fixes)[/-] ]] || [[ "$BRANCH_NAME" =~ ^dev(elop)?(ment)?$ ]]; then
          IS_PREVIEW_BRANCH=true
        fi
        
        # Use GitVersion's calculated values directly
        MAJOR_MINOR_PATCH="${{ steps.gitversion.outputs.majorMinorPatch }}"
        CALCULATED_PATCH="$BASE_PATCH"
        BASE_VERSION="$MAJOR_MINOR_PATCH"
        
        # For preview branches, ensure preview label is applied
        if [ "$IS_PREVIEW_BRANCH" = true ]; then
          if [ -z "$PRE_RELEASE_LABEL" ]; then
            # GitVersion didn't apply label, add preview manually
            FORMATTED_VERSION="${MAJOR_MINOR_PATCH}-preview"
          else
            # GitVersion applied a label, use it
            FORMATTED_VERSION="${MAJOR_MINOR_PATCH}-${PRE_RELEASE_LABEL}"
          fi
        else
          # Non-preview branches: use GitVersion's output as-is
          if [ -n "$PRE_RELEASE_LABEL" ]; then
            FORMATTED_VERSION="${MAJOR_MINOR_PATCH}-${PRE_RELEASE_LABEL}"
          else
            FORMATTED_VERSION="$MAJOR_MINOR_PATCH"
          fi
        fi
        
        echo "formatted_version=$FORMATTED_VERSION" >> $GITHUB_OUTPUT
        echo "base_version=$BASE_VERSION" >> $GITHUB_OUTPUT
        echo "sem_ver=$ORIGINAL_SEMVER" >> $GITHUB_OUTPUT
        echo "full_sem_ver=${{ steps.gitversion.outputs.fullSemVer }}" >> $GITHUB_OUTPUT
        echo "assembly_sem_ver=${{ steps.gitversion.outputs.assemblySemVer }}" >> $GITHUB_OUTPUT
        echo "assembly_sem_file_ver=${{ steps.gitversion.outputs.assemblySemFileVer }}" >> $GITHUB_OUTPUT
        echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        echo "major=$MAJOR" >> $GITHUB_OUTPUT
        echo "minor=$MINOR" >> $GITHUB_OUTPUT
        echo "patch=$CALCULATED_PATCH" >> $GITHUB_OUTPUT
        
        # Check if it's a pre-release
        if [ "$IS_PREVIEW_BRANCH" = true ] || [ -n "$PRE_RELEASE_LABEL" ]; then
          echo "is_prerelease=true" >> $GITHUB_OUTPUT
        else
          echo "is_prerelease=false" >> $GITHUB_OUTPUT
        fi
        
        echo "✅ Version: $FORMATTED_VERSION"
        echo "   Base version: $BASE_VERSION"
        echo "   Branch: $BRANCH_NAME"
        echo "   GitVersion SemVer: $ORIGINAL_SEMVER"
        if [ "$IS_PREVIEW_BRANCH" = true ]; then
          echo "   Preview branch detected"
        fi

